### ISSUE TITLE
SECURITY: Threshold value is ignored (all shares are n=3).

### ISSUE THREAD

**Issue by cyphar** [Nebulosus/shamir#3]
There is a pretty serious bug in `SecretData::with_secret` -- all sharded secrets (no matter the threshold setting) will require three shares to reconstruct the secret. Here's an example:

```rust
extern crate shamir;

use shamir::SecretData;

fn try_recover(n: u8, shares: &Vec<Vec<u8>>) -> Option<String> {
    let shares = shares.iter().take(n as usize).cloned().collect::<Vec<_>>();
    SecretData::recover_secret(n, shares)
}

fn main() {
    let secret_data = SecretData::with_secret("Hello World!", 5);

    let shares = vec![
        secret_data.get_share(1),
        secret_data.get_share(2),
        secret_data.get_share(3),
        secret_data.get_share(4),
        secret_data.get_share(5),
    ];

    let recovered = try_recover(5, &shares).unwrap();
    println!("Good recover: {}", recovered);

    let recovered = try_recover(3, &shares).unwrap();
    println!("Bad recover: {}", recovered);
}
```

The reason for this bug is this line from `with_secret`:

```rust
        let mut rand_container = [0u8, threshold - 1];
```

This leads to only three coefficients being generated for the polynomial (resulting in an `n=3` threshold system). I presume this was meant to be `[0u8; threshold - 1]` (an array of zeroes of `threshold - 1` size) but this won't work in Rust -- instead you should use something like `vec![0; threshold - 1]`.

I'm a also quite a bit worried by the very minimal test-cases (failure to reconstruct isn't checked, and the only threshold tests are for `3` shares -- this bug would've been obvious if there was a test for `2` shares). As it stands, I would humbly suggest that you yank all releases of `shamir` and make a new release which fixes this problem (or, since it seems this crate is abandoned, just leave it yanked).

/cc @ChrisMacNaughton

**Comment by ChrisMacNaughton** [comment]
I'm going to wrap up one more bit of maintainance and I'll get it updated on crates.io as well

**Comment by Shnatsel** [comment]
Since this is a security bug, you might want to open a security advisory about it: https://github.com/RustSec/advisory-db

This way downstream users of the crate will be able to check if they depend on a vulnerable version and upgrade.
